CREATE TABLE IF NOT EXISTS `Log_TABLE` (
  `_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `CallSign` varchar(20) DEFAULT NULL,
  `QSODate` datetime DEFAULT NULL,
  `QSOTime` varchar(5) DEFAULT NULL,
  `QSOBand` varchar(10) DEFAULT NULL,
  `QSOMode` varchar(7) DEFAULT NULL,
  `QSOReportSent` varchar(15) DEFAULT NULL,
  `QSOReportRecived` varchar(15) DEFAULT NULL,
  `OMName` varchar(20) DEFAULT NULL,
  `OMQTH` varchar(25) DEFAULT NULL,
  `State` varchar(25) DEFAULT NULL,
  `Grid` varchar(6) DEFAULT NULL,
  `IOTA` varchar(6) DEFAULT NULL,
  `QSLManager` varchar(9) DEFAULT NULL,
  `QSLSent` tinyint(1) DEFAULT NULL,
  `QSLSentAdv` varchar(1) DEFAULT NULL,
  `QSLSentDate` datetime DEFAULT NULL,
  `QSLRec` tinyint(1) DEFAULT NULL,
  `QSLRecDate` datetime DEFAULT NULL,
  `MainPrefix` varchar(5) DEFAULT NULL,
  `DXCCPrefix` varchar(5) DEFAULT NULL,
  `CQZone` varchar(2) DEFAULT NULL,
  `ITUZone` varchar(2) DEFAULT NULL,
  `QSOAddInfo` longtext,
  `Marker` int(11) DEFAULT NULL,
  `ManualSet` tinyint(1) DEFAULT NULL,
  `DigiBand` double DEFAULT NULL,
  `Continent` varchar(2) DEFAULT NULL,
  `ShortNote` varchar(30) DEFAULT NULL,
  `QSLReceQSLcc` tinyint(1) DEFAULT NULL,
  `LoTWRec` tinyint(1) DEFAULT NULL,
  `LoTWRecDate` datetime DEFAULT NULL,
  `QSLInfo` varchar(100) DEFAULT NULL,
  `Call` varchar(20) DEFAULT NULL,
  `State1` varchar(25) DEFAULT NULL,
  `State2` varchar(25) DEFAULT NULL,
  `State3` varchar(25) DEFAULT NULL,
  `State4` varchar(25) DEFAULT NULL,
  `WPX` varchar(10) DEFAULT NULL,
  `AwardsEx` longtext,
  `ValidDX` tinyint(1) DEFAULT NULL,
  `SRX` int(11) DEFAULT NULL,
  `SRX_STRING` varchar(15) DEFAULT NULL,
  `STX` int(11) DEFAULT NULL,
  `STX_STRING` varchar(15) DEFAULT NULL,
  `SAT_NAME` varchar(20) DEFAULT NULL,
  `SAT_MODE` varchar(20) DEFAULT NULL,
  `PROP_MODE` varchar(20) DEFAULT NULL,
  `LoTWSent` tinyint(1) DEFAULT NULL,
  `QSL_RCVD_VIA` varchar(1) DEFAULT NULL,
  `QSL_SENT_VIA` varchar(1) DEFAULT NULL,
  `DXCC` varchar(5) DEFAULT NULL,
  `USERS` varchar(5) DEFAULT NULL,
  `NoCalcDXCC` tinyint(1) DEFAULT NULL
);

