INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2641, 'CT', 'МИНСК - ЦЕНТРАЛЬНЫЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2642, 'FR', 'МИНСК - ФРУНЗЕНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2643, 'LE', 'МИНСК - ЛЕНИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2644, 'MO', 'МИНСК - МОСКОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2645, 'OK', 'МИНСК - ОКТЯБРЬСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2646, 'PA', 'МИНСК - ПАРТИЗАНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2647, 'PM', 'МИНСК - ПЕРВОМАЙСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2648, 'SO', 'МИНСК - СОВЕТСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2649, 'ZA', 'МИНСК - ЗАВОДСКОЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2650, 'BI', 'БОРИСОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2651, 'BZ', 'БЕРЕЗИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2652, 'DZ', 'ДЗЕРЖИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2653, 'ER', 'ЧЕРВЕНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2654, 'KC', 'КЛЕЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2655, 'KL', 'КОПЫЛЬСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2656, 'KU', 'КРУПСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2657, 'LG', 'ЛОГОЙСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2658, 'LK', 'ЛЮБАНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2659, 'MD', 'МОЛОДЕЧЕНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2660, 'ME', 'МЯДЕЛЬСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2661, 'MI', 'МИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2662, 'NE', 'НЕСВЕЖСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2663, 'PU', 'ПУХОВИЧСКИЙ ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2664, 'SB', 'СТОЛБЦОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2665, 'SD', 'СТАРОДОРОЖНЫЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2666, 'SG', 'СОЛИГОРСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2667, 'SL', 'СЛУЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2668, 'SM', 'СМОЛЕВИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2669, 'UZ', 'УЗДЕНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2670, 'WL', 'ВИЛЕЙСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2671, 'WO', 'ВОЛОЖИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2672, 'BA', 'БАРАНОВИЧСКИЙ ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2673, 'BE', 'БЕРЕЗОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2674, 'BR', 'БРЕСТСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2675, 'DR', 'ДРОГИЧИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2676, 'GA', 'ГАНЦЕВИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2677, 'IC', 'ИВАЦЕВИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2678, 'IW', 'ИВАНОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2679, 'KA', 'КАМЕНЕЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2680, 'KO', 'КОБРИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2681, 'LH', 'ЛЯХОВИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2682, 'LN', 'БРЕСТ - ЛЕНИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2683, 'LU', 'ЛУНИНЕЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2684, 'MA', 'МАЛОРИЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2685, 'MK', 'БРЕСТ - МОСКОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2686, 'PI', 'ПИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2687, 'PV', 'ПРУЖАНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2688, 'ST', 'СТОЛИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2689, 'VA', 'ЖАБИНКОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2690, 'BW', 'БЕРЕСТОВИЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2691, 'DT', 'ДЯТЛОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2692, 'GK', 'ГРОДНЕНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2693, 'IX', 'ИВЬЕВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2694, 'KJ', 'КОРЕЛИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2695, 'LI', 'ЛИДСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2696, 'LS', 'ГРОДНО - ЛЕНИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2697, 'MW', 'МОСТОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2698, 'NG', 'НОВОГРУДСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2699, 'ON', 'ОШМЯНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2700, 'OT', 'ГРОДНО - ОКТЯБРЬСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2701, 'OW', 'ОСТРОВЕЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2702, 'QU', 'ЩУЧИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2703, 'SJ', 'СЛОНИМСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2704, 'SN', 'СМОРГОНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2705, 'SS', 'СВИСЛОЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2706, 'WR', 'ВОРОНОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2707, 'WW', 'ВОЛКОВЫССКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2708, 'ZE', 'ЗЕЛЬВЕНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2709, 'AN', 'ЧАШНИЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2710, 'AR', 'ШАРКОВЩИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2711, 'BN', 'БЕШЕНКОВИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2712, 'BS', 'БРАСЛАВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2713, 'DO', 'ДОКШИЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2714, 'DU', 'ДУБРОВЕНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2715, 'GD', 'ГОРОДОКСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2716, 'GL', 'ГЛУБОКСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2717, 'LP', 'ЛЕПЕЛЬСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2718, 'LZ', 'ЛИОЗНЕНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2719, 'MR', 'МИОРСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2720, 'OA', 'ОРШАНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2721, 'OB', 'ВИТЕБСК - ОКТЯБОРЬСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2722, 'PO', 'ПОЛОЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2723, 'PR', 'ВИТЕБСК - ПЕРВОМАЙСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2724, 'PS', 'ПОСТАВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2725, 'RS', 'РОССОНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2726, 'SE', 'СЕННЕНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2727, 'TO', 'ТОЛОЧИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2728, 'UA', 'УШАЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2729, 'UM', 'ШУМИЛИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2730, 'VE', 'ВИТЕБСК - ЖЕЛЕЗНОДОРОЖНЫЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2731, 'WD', 'ВЕРХНЕДВИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2732, 'WI', 'ВИТЕБСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2733, 'AU', 'ЧАУССКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2734, 'BL', 'БЕЛЫНИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2735, 'BO', 'БОБРУЙСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2736, 'BY', 'БЫХОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2737, 'OR', 'МОГИЛЕВ - ОКТЯБРЬСКИЙ ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2738, 'DN', 'ДРИБИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2739, 'EI', 'ЧЕРИКОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2740, 'GR', 'ГОРЕЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2741, 'GS', 'ГЛУССКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2742, 'HT', 'ХОТИМСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2743, 'KE', 'КЛИЧЕВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2744, 'KG', 'КРУГЛЯНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2745, 'KI', 'КИРОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2746, 'KM', 'КЛИМОВИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2747, 'KP', 'КРАСНОПОЛЬСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2748, 'KS', 'КОСТЮКОВИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2749, 'KW', 'КРИЧЕВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2750, 'LB', 'БОБРУЙСК - ЛЕНИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2751, 'LM', 'МОГИЛЕВ - ЛЕНИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2752, 'MG', 'МОГИЛЕВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2753, 'MS', 'МСТИСЛАВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2754, 'OP', 'ОСИПОВИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2755, 'PW', 'БОБРУЙСК - ПЕРВОМАЙСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2756, 'SA', 'СЛАВГОРОДСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2757, 'WS', 'ШКОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2758, 'BG', 'БРАГИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2759, 'BK', 'БУДА-КОШЕЛЕВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2760, 'CE', 'ГОМЕЛЬ - ЦЕНТРАЛЬНЫЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2761, 'DB', 'ДОБРУШСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2762, 'EE', 'ЧЕЧЕРСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2763, 'EL', 'ЕЛЬСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2764, 'GO', 'ГОМЕЛЬСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2765, 'HO', 'ХОЙНИКСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2766, 'KN', 'КАЛИНКОВИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2767, 'KR', 'КОРМЯНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2768, 'LL', 'ЛЕЛЬЧИЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2769, 'LO', 'ЛОЕВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2770, 'MZ', 'МОЗЫРСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2771, 'NA', 'НАРОВЛЯНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2772, 'NB', 'ГОМЕЛЬ - НОВОБЕЛИЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2773, 'OS', 'ОКТЯБРЬСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2774, 'PE', 'ПЕТРИКОВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2775, 'RE', 'РЕЧИЦКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2776, 'RG', 'РОГАЧЕВСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2777, 'SK', 'ГОМЕЛЬ - СОВЕТСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2778, 'SW', 'СВЕТЛОГОРСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2779, 'VD', 'ГОМЕЛЬ - ЖЕЛЕЗНОДОРОЖНЫЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2780, 'VI', 'ЖИДКОВИЧСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2781, 'VL', 'ЖЛОБИНСКИЙ');
INSERT INTO `STATE` (`_id`, `STATE`, `Name`) VALUES (2782, 'WE', 'ВЕТКОВСКИЙ');